// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Angajat {
	/**
	 * 
	 */
	public Angajat(boolean isManager, String nume, String prenume, String username, String parola, int idAngajat) {
		this.isManager = isManager;
		this.nume = nume;
		this.prenume = prenume;
		this.username = username;
		this.parola = parola;
		this.idAngajat = idAngajat;
	}
	
	private boolean isManager;
	/**
	 * 
	 */
	private String nume;
	public void setParola(String parola) {
		this.parola = parola;
	}

	/**
	 * 
	 */
	private String prenume;
	/**
	 * 
	 */
	private String username;
	public String getUsername() {
		return username;
	}

	public String getParola() {
		return parola;
	}

	/**
	 * 
	 */
	private String parola;
	/**
	 * 
	 */
	private int idAngajat;

	/**
	 * @return 
	 * 
	 */
	public boolean isManager() {
		return this.isManager;
	}
}
