// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Angajat {
	/**
	 * 
	 */
	private boolean isManager;
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String prenume;
	/**
	 * 
	 */
	private String username;
	/**
	 * 
	 */
	private String parola;
	/**
	 * 
	 */
	private int idAngajat;

	/**
	 * 
	 */
	public void isManager() {
	}
}
