// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class BazaDeDate {
	/**
	 * 
	 */
	protected static int nrSedinte = 0;
	/**
	 * 
	 */
	protected static int nrAngajati = 0;
	/**
	 * 
	 */
	protected Sedinta[] sedinta = new Sedinta[100];
	/**
	 * 
	 */
	protected Angajat[] angajat = new Angajat[100];
}
