// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

public class BazaDeDate {
	protected int nrSedinte = 0;
	protected int nrAngajati = 0;
	
	private static final int maxNrOfElements = 20;
	
	protected Sedinta[] sedinte = new Sedinta[maxNrOfElements];
	protected Angajat[] angajati = new Angajat[maxNrOfElements];
	
	public BazaDeDate() {
		this.populate();
	}
	
	// Metoda de adaugare a unei sedinte noi
	protected void addSedinta(Sedinta sedinta) {
		this.sedinte[nrSedinte] = sedinta;
		this.nrSedinte++;
	}
	
	// Metoda de adaugare a unui angajat nou
	protected void addAngajat(Angajat angajat) {
		this.angajati[nrAngajati] = angajat;
		this.nrAngajati++;
	}
	
	// Metoda de a obtine un angajat din baza de date dupa id
	protected Angajat getAngajatByID(int id) {
		for(Angajat a : this.angajati) {
			if(a.getID() == id) {
				return a;
			}
		}
		return null;
	}
	
	// Metoda de a obtine o sedinta din baza de date dupa id
	protected Sedinta getSedintaByID(int id) {
		for(Sedinta s : this.sedinte) {
			if(s.getIdSedinta() == id) {
				return s;
			}
		}
		return null;
	}
	
	public Sedinta[] getSedinte() {
		return this.sedinte;
	}
	
	public Angajat[] getAngajati() {
		return this.angajati;
	}
	
	// Metoda de populare a bazei de date pentru o ulterioara testare
	private void populate() {
		this.nrAngajati = 10;
		this.nrSedinte = 3;
		
		this.angajati[0] = new Angajat(true, "Popescu", "Andrei", "PAndrei", "1234", 0);
		this.angajati[1] = new Angajat(false, "Ionescu", "Andrei", "IAndrei", "1334", 1);
		this.angajati[2] = new Angajat(false, "Matei", "Corvin", "MCRV", "1111", 2);
		this.angajati[3] = new Angajat(false, "Sandu", "Dorel", "DoruS", "1222", 3);
		this.angajati[4] = new Angajat(false, "Unguru", "Mihai", "UMihai", "1234", 4);
		this.angajati[5] = new Angajat(false, "Iliescu", "Alexandru", "IlieA", "4321", 5);
		this.angajati[6] = new Angajat(true, "Andrei", "Andrei", "AndreiAndrei", "Andrei", 6);
		this.angajati[7] = new Angajat(false, "Paun", "Sebastian", "Sebi", "6234", 7);
		this.angajati[8] = new Angajat(false, "Popescu", "Maria", "MariaP", "124325", 8);
		this.angajati[9] = new Angajat(false, "Ionescu", "Andreeea", "AndreeaI", "1233523454", 9);
		
		this.sedinte[0] = new Sedinta("NXP Cup", "Discutie despre organizarea", "18-05-2023", "16:00", "Popescu", "C310");
		this.sedinte[1] = new Sedinta("Nokia", "Q&A intern", "17-05-2023", "13:00", "Andrei", "ED002");
		this.sedinte[2] = new Sedinta("Ixia Innov", "Sedinta tactica", "19-05-2023", "10:00", "Andrei", "B08");
		
		this.sedinte[0].adaugareAngajatSedinta(this.angajati[0]);
		this.sedinte[0].adaugareAngajatSedinta(this.angajati[1]);
		this.sedinte[0].adaugareAngajatSedinta(this.angajati[2]);
		this.sedinte[0].adaugareAngajatSedinta(this.angajati[3]);
		
		this.sedinte[1].adaugareAngajatSedinta(this.angajati[4]);
		this.sedinte[1].adaugareAngajatSedinta(this.angajati[5]);
		this.sedinte[1].adaugareAngajatSedinta(this.angajati[6]);
		
		this.sedinte[2].adaugareAngajatSedinta(this.angajati[6]);
		this.sedinte[2].adaugareAngajatSedinta(this.angajati[7]);
		this.sedinte[2].adaugareAngajatSedinta(this.angajati[8]);
		this.sedinte[2].adaugareAngajatSedinta(this.angajati[9]);
	}
}
