// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Scanner;

public class MeniuGestionareSedinta extends Meniu {
	private int idSedintaSelectata; //salvez sedinta pe care o modific
	
	public MeniuGestionareSedinta() {
		super();
	}
	
	public int getIdSedintaSelectata() {
		return this.idSedintaSelectata;
	}

	public void afisare() {
		System.out.println("Date despre sedinta selectata: ");
		super.getSedintaByID(idSedintaSelectata).afisare();
		
		this.afisareOptiuni();
	}

	@SuppressWarnings("resource")
	private void afisareOptiuni() {
	    System.out.println("Alege o optiune:");
	    System.out.println("1 - Acceptare sedinta");
	    System.out.println("2 - Refuz, propunere data si ora nou:");
	    System.out.println("X - Intoarcere la meniul anterior");

	    Scanner kbd = new Scanner(System.in);
	    String optiune = kbd.nextLine().toUpperCase();

	    switch(optiune) {
	        case "1":
	            kbd.nextLine();
	            System.out.println("Introduceti statusul pentru acceptarea sedintei (e.g., 'approved'):");
	            String status = kbd.nextLine();
	            this.acceptareSedinta(status);
	            super.urmatorulMeniu = TipuriMeniu.MeniuGestionareSedinta;
	            break;
	        case "2":
	            kbd.nextLine();
	            System.out.println("Introduceti noua data si ora pentru sedinta:");
	            System.out.print("Data: ");
	            String data = kbd.nextLine();
	            System.out.print("Ora: ");
	            String ora = kbd.nextLine();
	            this.alegereDataOraNoua(data, ora);
	            super.urmatorulMeniu = TipuriMeniu.MeniuGestionareSedinta;
	            break;
	        case "X":
	            super.urmatorulMeniu = TipuriMeniu.MeniuDefault;
	            return;
	        default:
	            System.out.println("Optiune invalida. Te rog sa introduci '1', '2', '3' sau 'X'.");
	            afisareOptiuni();
	    }
	    kbd.close();
	}


	public void alegereDataOraNoua(String data, String ora) {
		super.sedinte[idSedintaSelectata].propunereNoua(data, ora);
	}

	public void acceptareSedinta(String status) {
		super.sedinte[idSedintaSelectata].setStatus(status);
	}

	public void selectareSedinta(int idSedintaSelectata) {
		this.idSedintaSelectata = idSedintaSelectata; //modific sedinta selectata de angajat pentru verificare
	}
	
} 