// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Scanner;

public class MeniuAngajat extends Meniu {
	public MeniuAngajat() {
		super();
	}
	
	public void afisare() {
		this.afisareNotificari();
		System.out.println("");
		this.afisareOptiuni();
	}

	private void afisareNotificari() {
		System.out.println("Notificari:");
		for(Sedinta s : super.sedinte) {
			if(s.isParticipant(idAngajatLogat) && s.isPending()) {
				s.afisareDreptNotificare();
			}
		}
	}

	private void afisareOptiuni() {
	    System.out.println("Alege o optiune:");
	    System.out.println("1. Schimbare parola");
	    System.out.println("2. Vizualizare si gestionare sedinte");
	    System.out.println("3. Intoarcere la meniul principal");

	    Scanner scanner = new Scanner(System.in);
	    int optiune = scanner.nextInt();

	    switch(optiune) {
	        case 1:
	            System.out.println("Introdu noua parola:");
	            String parola = scanner.next();
	            schimbareParola(parola);
	            urmatorulMeniu = TipuriMeniu.MeniuAngajat;
	            break;
	        case 2:
	            urmatorulMeniu = TipuriMeniu.MeniuSedinte;
	            break;
	        case 3:
	        	urmatorulMeniu = TipuriMeniu.MeniuDefault;
	            return;
	        default:
	            System.out.println("Optiune invalida. Te rog sa alegi 1, 2 sau 3.");
	            afisareOptiuni();
	    }
	}


	private void schimbareParola(String parola) {
		angajati[this.idAngajatLogat].setParola(parola);
		
		System.out.println("Parola a fosts chimbata cu succes");
	}
}
