// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class MeniuAngajat extends Meniu {
	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	private void afisareNotificari() {
	}

	/**
	 * 
	 */
	private void afisareOptiuni() {
	}

	/**
	 * 
	 */
	private void schimbareParola() {
	}
}
