// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class MeniuGestionareSedinta extends Meniu {
	/**
	 * 
	 */
	private int idSedintaSelectata;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	private void afisareOptiuni() {
	}

	/**
	 * 
	 * @param data 
	 * @param ora 
	 */
	private void alegereDataOraNoua(String data, String ora) {
	}

	/**
	 * 
	 */
	private void acceptareSedinta() {
	}

	/**
	 * 
	 * @param idSedintaSelectata 
	 */
	public void SelectareSedinta(int idSedintaSelectata) {
	}
}
