// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class MeniuLogare extends Meniu {
	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	private void logare() {
	}

	/**
	 * 
	 */
	private void afisareOptiuni() {
	}
}
