// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class MeniuManager extends MeniuAngajat {
	/**
	 * 
	 */
	private int idSedintaSelectata;

	/**
	 * 
	 */
	private void afisareOptiuni() {
		System.out.println("selectareSedinta");
		System.out.println("editareSedinta");
		System.out.println("inregistrareAngajatNou");
		System.out.println("afisare");
	}

	/**
	 * 
	 */
	public void afisare() {
		this.afisareOptiuni();
	}

	/**
	 * 
	 */
	private void inregistrareAngajatNou(Angajat a) {
		angajat[nrAngajati++] = a;
	}
	/**
	 * 
	 * @param titlu 
	 * @param descriere 
	 * @param data 
	 * @param ora 
	 * @param sala 
	 */
	public void editareSedinta(String titlu, String descriere, String data, String ora, String sala) {
		sedinta[idSedintaSelectata].setTitlu(titlu);
		sedinta[idSedintaSelectata].setDescriere(descriere);
		sedinta[idSedintaSelectata].setData(data);
		sedinta[idSedintaSelectata].setOra(ora);
		sedinta[idSedintaSelectata].setSala(sala);
	}

	/**
	 * 
	 * @param idSedintaSelectata 
	 */
	public void selectareSedinta(int idSedintaSelectata) {
		this.idSedintaSelectata = idSedintaSelectata;
	}
}
