// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class MeniuCreareSedinte extends Meniu {
	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	private void afisareOptiuni() {
	}

	/**
	 * 
	 * @param titlu 
	 * @param descriere 
	 * @param data 
	 * @param ora 
	 * @param manager 
	 * @param sala 
	 */
	public void creareSedinta(String titlu, String descriere, String data, String ora, String manager, String sala) {
	}
}
