// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Meniu extends BazaDeDate {
	/**
	 * 
	 */
	protected int idAngajatLogat = -1;
	/**
	 * 
	 */
	public TipuriMeniu urmatorulMeniu;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	private void afisareOptiuni() {
	}

	/**
	 * 
	 */
	public void getUrmatorulMeniu() {
	}
}
