// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class MeniuSedinte extends Meniu {
	/**
	 * 
	 */
	private Sedinta sedintaCurenta;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	private void afisareOptiuni() {
	}

	/**
	 * 
	 * @param idSedinta 
	 */
	private void selectareSedinta(int idSedinta) {
	}

	/**
	 * 
	 */
	public void getSedinta() {
	}
}
