// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class MeniuManager extends MeniuAngajat {
	/**
	 * 
	 */
	private int idSedintaSelctata;

	/**
	 * 
	 */
	private void afisareOptiuni() {
	}

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	private void inregistrareAngajatNou() {
	}

	/**
	 * 
	 * @param titlu 
	 * @param descriere 
	 * @param data 
	 * @param ora 
	 * @param sala 
	 */
	public void editareSedinta(String titlu, String descriere, String data, String ora, String sala) {
	}

	/**
	 * 
	 * @param idSedintaSelectata 
	 */
	public void selectareSedinta(int idSedintaSelectata) {
	}
}
