// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Map;


/************************************************************/
/**
 * 
 */
public class Sedinta {
	/**
	 * 
	 */
	public Sedinta(String titlu, String descriere, String data, String ora, String manager, int idSedinta, String status, String sala) {
		this.titlu = titlu;
		this.descriere = descriere;
		this.data = data;
		this.ora = ora;
		this.manager = manager;
		this.idSedinta = idSedinta;
		this.status = status;
		this.sala = sala;
	}
	
	
	private String titlu;
	/**
	 * 
	 */
	private String descriere;
	/**
	 * 
	 */
	private String data;
	/**
	 * 
	 */
	private String ora;
	/**
	 * 
	 */
	private String manager;
	/**
	 * 
	 */
	private int idSedinta;
	/**
	 * 
	 */
	private String status;
	/**
	 * 
	 */
	private static int nrPropuneri;
	
	public void propunereNoua(String dataNoua, String oraNoua) {
		propuneriData[nrPropuneri] = dataNoua;
		propuneriOra[nrPropuneri] = oraNoua;
		nrPropuneri++;
	}
	
	private String[] propuneriData = new String[100];
	
	private String[] propuneriOra = new String[100];
	
	/**
	 * 
	 */
	private String sala;
	/**
	 * 
	 */
	private Angajat[] angajat = new Angajat[100];

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	public void afisareDreptNotificare() {
	}

	/**
	 * 
	 */
	public void isPending() {
	}
}
