// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Map;

/************************************************************/
/**
 * 
 */
public class Sedinta {
	/**
	 * 
	 */
	private String titlu;
	/**
	 * 
	 */
	private String descriere;
	/**
	 * 
	 */
	private String data;
	/**
	 * 
	 */
	private String ora;
	/**
	 * 
	 */
	private String manager;
	/**
	 * 
	 */
	private int idSedinta;
	/**
	 * 
	 */
	private String status;
	/**
	 * 
	 */
	private Map propuneriDataOra;
	/**
	 * 
	 */
	private String sala;
	/**
	 * 
	 */
	private Angajat[] angajat;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	public void afisareDreptNotificare() {
	}

	/**
	 * 
	 */
	public void isPending() {
	}
}
