// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

public enum TipuriMeniu {
	MeniuDefault,
	
	MeniuSedinte,
	
	MeniuAngajat,
	
	MeniuManager,
	
	MeniuLogare,

	MeniuGestionareSedinta,
	
	MeniuCreareSedinte;
}
